/**
 * Parser for EverQuest character inventory dumps
 * Generated by the EQ client command: /outputfile inventory <filename>.txt
 * 
 * Hierarchy & Rules:
 * - Only parse items from inventory bags (General 1-12) and bank (Bank1-24, SharedBank1-6).
 * - Exclude worn equipped gear (Primary, Secondary, Head, Chest, Ear, etc.).
 * - Exclude KeyRing, Augmentation, Equipment (wardrobe), and Activated sections.
 * - Identify socketed sub-slots:
 *     Slot2: Ornamentation (appearance)
 *     Slot7: Focus Effect exaltation
 *     Slot8: Click Effect exaltation
 *     Slot9: Worn Effect exaltation
 *     Slot10: Proc Effect exaltation
 *     Slot1: Augmentation / General socket
 * - Attach non-empty socketed items to their parent gear item.
 * - Loose exaltations sitting in bags (e.g. Wakizashi of the Frozen Skies (Exaltation))
 *   are preserved as independent inventory items available for donation.
 */

const SLOT_TYPES = {
  1: 'aug',
  2: 'ornamentation',
  7: 'focus',
  8: 'click',
  9: 'worn',
  10: 'proc'
};

const SLOT_LABELS = {
  ornamentation: 'Ornament',
  focus: 'Focus',
  click: 'Click',
  worn: 'Worn',
  proc: 'Proc',
  aug: 'Aug'
};

function formatExaltsSummary(exalts) {
  if (!exalts) return '';
  const parts = [];
  if (exalts.ornamentation) parts.push(`🎨 ${SLOT_LABELS.ornamentation}: ${exalts.ornamentation.replace(/\s*\((?:Ornamentation|Exaltation)\)/i, '')}`);
  if (exalts.focus) parts.push(`🎯 ${SLOT_LABELS.focus}: ${exalts.focus.replace(/\s*\((?:Ornamentation|Exaltation)\)/i, '')}`);
  if (exalts.click) parts.push(`✨ ${SLOT_LABELS.click}: ${exalts.click.replace(/\s*\((?:Ornamentation|Exaltation)\)/i, '')}`);
  if (exalts.worn) parts.push(`🛡️ ${SLOT_LABELS.worn}: ${exalts.worn.replace(/\s*\((?:Ornamentation|Exaltation)\)/i, '')}`);
  if (exalts.proc) parts.push(`⚡ ${SLOT_LABELS.proc}: ${exalts.proc.replace(/\s*\((?:Ornamentation|Exaltation)\)/i, '')}`);
  if (exalts.aug) parts.push(`💎 ${SLOT_LABELS.aug}: ${exalts.aug.replace(/\s*\((?:Ornamentation|Exaltation)\)/i, '')}`);
  return parts.length > 0 ? parts.join(' | ') : '';
}

function parseEqInventoryText(fileContent) {
  if (!fileContent || typeof fileContent !== 'string') {
    return [];
  }

  const lines = fileContent.split(/\r?\n/);
  const itemsByLocation = new Map();
  const itemsList = [];
  let inBagsOrBank = false;
  let colIndices = { location: 0, name: 1, id: 2, count: 3 };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;

    // Check for tab delimiter (standard) or multiple spaces
    let parts = line.split('\t');
    if (parts.length < 2) {
      parts = line.split(/\s{2,}/);
    }
    if (parts.length < 2) continue;

    const firstCol = parts[0].trim();
    const firstColLower = firstCol.toLowerCase();

    // Check if this line is the main inventory header
    if (firstColLower === 'location') {
      parts.forEach((p, idx) => {
        const lower = p.trim().toLowerCase();
        if (lower === 'location') colIndices.location = idx;
        else if (lower === 'name') colIndices.name = idx;
        else if (lower === 'id') colIndices.id = idx;
        else if (lower === 'count' || lower === 'qty' || lower === 'quantity') colIndices.count = idx;
      });
      continue;
    }

    // Stop completely if reaching non-inventory sections like KeyRing, Augmentation, Equipment
    if (firstCol === 'KeyRing' || firstColLower === 'keyring' || firstCol === 'Augmentation' || firstCol === 'Equipment' || firstCol === 'Activated') {
      break;
    }

    // STRICT FILTER: Only allow locations starting with General, Bank, or SharedBank
    if (!/^(General\s*\d+|Bank\d+|SharedBank\d+)/i.test(firstCol)) {
      continue;
    }

    // Skip top-level bag container definitions (e.g. "General 1", "General 2", "Bank1")
    // because those are the player's worn backpack containers holding the item slots.
    if (!firstCol.includes('-Slot')) {
      continue;
    }

    const location = firstCol;
    const rawName = (parts[colIndices.name] || '').trim();
    const rawId = (parts[colIndices.id] || '').trim();
    const rawCount = (parts[colIndices.count] || '1').trim();

    // Ignore empty slots
    if (!rawName || rawName.toLowerCase() === 'empty' || rawName.toLowerCase() === '(empty)') {
      continue;
    }

    // Ignore currency/coin if any
    if (/^(platinum|gold|silver|copper)\s*(pieces?)?$/i.test(rawName)) {
      continue;
    }

    // Check if this is a socketed sub-slot of an existing item
    // e.g., "General 3-Slot7-Slot2" has parent "General 3-Slot7" with slot 2 (Ornamentation)
    const lastSlotIdx = location.lastIndexOf('-Slot');
    const parentLoc = location.substring(0, lastSlotIdx);
    const slotNum = parseInt(location.substring(lastSlotIdx + 5), 10);

    const isSubSlot = itemsByLocation.has(parentLoc) && (
      Boolean(SLOT_TYPES[slotNum]) ||
      rawName.includes('(Ornamentation)') ||
      rawName.includes('(Exaltation)')
    );

    if (isSubSlot) {
      const parent = itemsByLocation.get(parentLoc);
      const slotType = SLOT_TYPES[slotNum] || `slot${slotNum}`;
      parent.exalts[slotType] = rawName;
      parent.hasExalts = true;
      continue;
    }

    // This is an independent inventory item (gear, loose exaltation, consumable, reagent)
    const count = Math.max(1, parseInt(rawCount, 10) || 1);

    // Parse upgrade tier (+0..+10) or quantity stack (x1..x1000)
    let upgradeLevel = '+0';
    let cleanItemName = rawName;

    const qtyMatch = rawName.match(/^(.*?)\s+[xX]\s*(\d+)$/);
    const plusMatch = rawName.match(/^(.*?)\s*(\+[1-9]|\+10)$/i);

    if (qtyMatch) {
      cleanItemName = qtyMatch[1].trim();
      upgradeLevel = `x${qtyMatch[2]}`;
    } else if (plusMatch) {
      cleanItemName = plusMatch[1].trim();
      upgradeLevel = plusMatch[2].toUpperCase();
    } else if (count > 1) {
      upgradeLevel = `x${count}`;
    }

    const itemObj = {
      location,
      rawName,
      cleanItemName,
      count,
      upgradeLevel,
      itemId: rawId || null,
      exalts: {
        ornamentation: null,
        focus: null,
        click: null,
        worn: null,
        proc: null,
        aug: null
      },
      hasExalts: false
    };

    itemsByLocation.set(location, itemObj);
    itemsList.push(itemObj);
  }

  return itemsList;
}

/**
 * Consolidate items for batch donation review
 * Items with socketed exalts are preserved individually with their specific attached exalts
 */
function groupInventoryItems(parsedItems) {
  const result = [];
  const standardMap = new Map();

  for (const item of parsedItems) {
    // If the item has socketed exalts/ornaments, keep it as its own distinct entry
    if (item.hasExalts) {
      result.push({
        cleanItemName: item.cleanItemName,
        upgradeLevel: item.upgradeLevel,
        locations: [item.location],
        totalCount: item.count,
        sampleItemId: item.itemId,
        exalts: item.exalts,
        hasExalts: true,
        exaltsSummary: formatExaltsSummary(item.exalts)
      });
      continue;
    }

    // Otherwise group identical plain items / stacks
    const key = `${item.cleanItemName.toLowerCase()}||${item.upgradeLevel}`;
    if (!standardMap.has(key)) {
      standardMap.set(key, {
        cleanItemName: item.cleanItemName,
        upgradeLevel: item.upgradeLevel,
        locations: [item.location],
        totalCount: item.count,
        sampleItemId: item.itemId,
        exalts: null,
        hasExalts: false,
        exaltsSummary: ''
      });
    } else {
      const existing = standardMap.get(key);
      existing.locations.push(item.location);
      existing.totalCount += item.count;
    }
  }

  for (const grouped of standardMap.values()) {
    result.push(grouped);
  }

  return result;
}

module.exports = {
  parseEqInventoryText,
  groupInventoryItems,
  formatExaltsSummary,
  SLOT_TYPES,
  SLOT_LABELS
};
